=== BackupTheBerlios/bvr20983-svn/trunk/inc/ver/versions.dtd
<!-- $Id$ -->

<!ELEMENT versions ( product,guid+,filename+ ) >

<!ELEMENT product (name?,company?,copyright?,version?) >

<!ELEMENT name      (#PCDATA)>
<!ELEMENT company   (#PCDATA)>
<!ELEMENT copyright (#PCDATA)>


<!ELEMENT version EMPTY >
<!ATTLIST version major CDATA #REQUIRED >
<!ATTLIST version minor CDATA #REQUIRED >
<!ATTLIST version fix   CDATA #REQUIRED >
<!ATTLIST version rev   CDATA #REQUIRED >

<!ELEMENT guid EMPTY >
<!ATTLIST guid id ID    #REQUIRED >
<!ATTLIST guid g0 CDATA #REQUIRED >
<!ATTLIST guid g1 CDATA #REQUIRED >
<!ATTLIST guid g2 CDATA #REQUIRED >
<!ATTLIST guid g3 CDATA #REQUIRED >
<!ATTLIST guid g4 CDATA #REQUIRED >

<!ELEMENT filename (name,version?) >
<!ATTLIST filename type ( dll | exe | cab ) #REQUIRED >

=== BackupTheBerlios/bvr20983-svn/trunk/inc/ver/versions.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!-- 
     $Id$
     
     Copyright (C) 2008 Dorothea Wachmann
     
     This program is free software: you can redistribute it and/or modify
     it under the terms of the GNU General Public License as published by
     the Free Software Foundation, either version 3 of the License, or
     (at your option) any later version.
     
     This program is distributed in the hope that it will be useful,
     but WITHOUT ANY WARRANTY; without even the implied warranty of
     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
     GNU General Public License for more details.
     
     You should have received a copy of the GNU General Public License
     along with this program.  If not, see http://www.gnu.org/licenses/.
  -->
<!DOCTYPE versions SYSTEM "versions.dtd" [
  <!ENTITY product SYSTEM "product.xml" >
]>
<versions>

  &product;
  
  <guid id="a1" g0="7dc6e86d" g1="aaaa" g2="bbbb" g3="cccc" g4="425652200983"/> 
  <guid id="a2" g0="7dc6e86d" g1="aaaa" g2="bbbb" g3="cccc" g4="425652200983"/> 

  <filename type="dll"> 
    <name>BVR20983.DLL</name>
    <version major="1" minor="0" fix="0" rev="0"/>
  </filename>

  <filename type="dll"> 
    <name>BVR20983CC.DLL</name>
    <version major="1" minor="0" fix="0" rev="0"/>
  </filename>

  <filename type="cab"> 
    <name>BVR20983CC.CAB</name>
  </filename>
  
</versions>
